/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.DaoEmpresa;
import dao.DaoResiduo;
import dao.DaoUsuario;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.*;
import model.Empresa;
import model.Residuo;
import model.Usuario;

/**
 *
 * @author Takeshi
 */
public class FrmCadastrar extends javax.swing.JFrame {
    DaoEmpresa daoEmp = new DaoEmpresa();
    DaoResiduo daoRes = new DaoResiduo();
    DaoUsuario daoUser = new DaoUsuario();
    Empresa empresa = new Empresa();
    Usuario usuario = new Usuario();
    List<Residuo> residuos = new ArrayList<>();
    
    /**
     * Creates new form FrmCadastroTela
     */
    public FrmCadastrar() {
        initComponents();
        lblErroCampoNulo.setVisible(false); //TN Começa invisível, só aparece se errar. 
        lblErroCampoNuloEndereco.setVisible(false);
        lblErroTipoResiduo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPane = new javax.swing.JPanel();
        pessoaJuridica = new javax.swing.JPanel();
        pessoaJuridicaPane = new javax.swing.JPanel();
        lblTituloPessoaJuridica = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        btnCadastrar = new Swing.JButtonRound();
        txtSite = new javax.swing.JTextField();
        pwdConfirmarSenha = new javax.swing.JPasswordField();
        pwdSenha = new javax.swing.JPasswordField();
        txtNomeFantasia = new javax.swing.JTextField();
        lblErroCampoNulo = new javax.swing.JLabel();
        btnVoltarCadastro = new javax.swing.JLabel();
        lblfundoCadastro = new javax.swing.JLabel();
        endereco = new javax.swing.JPanel();
        encloseLocalizacao = new javax.swing.JPanel();
        lblTitleLocalizacao = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        txtUf = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        lblUf = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtCep = new javax.swing.JFormattedTextField();
        btnProximoEndereco = new Swing.JButtonRound();
        txtNumero = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblErroCampoNuloEndereco = new javax.swing.JLabel();
        btnVoltarEndereco = new javax.swing.JLabel();
        lblFundoLocalizacao = new javax.swing.JLabel();
        seuInteresse = new javax.swing.JPanel();
        btnVoltarInteresse = new javax.swing.JLabel();
        btnAdquirir = new javax.swing.JLabel();
        btnDescartar = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        tipoResiduos = new javax.swing.JPanel();
        lblTitleTiposResiduos = new javax.swing.JLabel();
        lblTitleTiposResiduos1 = new javax.swing.JLabel();
        btnVoltarTipoResiduos = new javax.swing.JLabel();
        btnProximoResiduo = new javax.swing.JButton();
        lblErroTipoResiduo = new javax.swing.JLabel();
        lblFundoTipoResiduos = new javax.swing.JLabel();
        lblCapacidadeMax1 = new javax.swing.JLabel();
        txtCapPapel = new javax.swing.JTextField();
        rbtnPlastico = new javax.swing.JRadioButton();
        lblKgMetal = new javax.swing.JLabel();
        txtCapVidro = new javax.swing.JTextField();
        rbtnVidro = new javax.swing.JRadioButton();
        txtCapMetal = new javax.swing.JTextField();
        txtPrecoVidro = new javax.swing.JTextField();
        rbtnPapel = new javax.swing.JRadioButton();
        rbtnMetal = new javax.swing.JRadioButton();
        lblKgPlastico = new javax.swing.JLabel();
        lblKgVidro = new javax.swing.JLabel();
        txtPrecoMetal = new javax.swing.JTextField();
        txtCapPlastico = new javax.swing.JTextField();
        lblKgMetal1 = new javax.swing.JLabel();
        lblKgPapel1 = new javax.swing.JLabel();
        lblTipos1 = new javax.swing.JLabel();
        lblKgPapel = new javax.swing.JLabel();
        txtPrecoPlastico = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPrecoPapel = new javax.swing.JTextField();
        lblKgVidro1 = new javax.swing.JLabel();
        lblKgPlastico1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardPane.setPreferredSize(new java.awt.Dimension(1366, 750));
        cardPane.setLayout(new java.awt.CardLayout());

        pessoaJuridica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pessoaJuridicaPane.setBackground(new java.awt.Color(255, 255, 255));
        pessoaJuridicaPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));

        lblTituloPessoaJuridica.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloPessoaJuridica.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTituloPessoaJuridica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPessoaJuridica.setText("PESSOA JURÍDICA");

        txtRazaoSocial.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "RAZÃO SOCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtCnpj.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "CNPJ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "EMAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtTelefone.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "TELEFONE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btnCadastrar.setBackground(new java.awt.Color(255, 153, 0));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setArc(20);
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtSite.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "SITE (opcional)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        pwdConfirmarSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "CONFIRMAR SENHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pwdConfirmarSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdConfirmarSenhaFocusLost(evt);
            }
        });

        pwdSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "SENHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pwdSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdSenhaFocusLost(evt);
            }
        });

        txtNomeFantasia.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "NOME FANTASIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblErroCampoNulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblErroCampoNulo.setForeground(new java.awt.Color(255, 0, 51));
        lblErroCampoNulo.setText("Preencha todos os campos obrigatórios");

        javax.swing.GroupLayout pessoaJuridicaPaneLayout = new javax.swing.GroupLayout(pessoaJuridicaPane);
        pessoaJuridicaPane.setLayout(pessoaJuridicaPaneLayout);
        pessoaJuridicaPaneLayout.setHorizontalGroup(
            pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(lblTituloPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRazaoSocial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNomeFantasia)
                            .addComponent(txtTelefone)
                            .addComponent(txtSite, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addComponent(pwdConfirmarSenha))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pessoaJuridicaPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pessoaJuridicaPaneLayout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(454, 454, 454))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pessoaJuridicaPaneLayout.createSequentialGroup()
                        .addComponent(lblErroCampoNulo, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(348, 348, 348))))
        );

        pessoaJuridicaPaneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCnpj, txtEmail, txtSite, txtTelefone});

        pessoaJuridicaPaneLayout.setVerticalGroup(
            pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErroCampoNulo)
                .addGap(15, 15, 15))
        );

        pessoaJuridica.add(pessoaJuridicaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 1110, 460));

        btnVoltarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltarVerde.png"))); // NOI18N
        btnVoltarCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarCadastroMouseExited(evt);
            }
        });
        pessoaJuridica.add(btnVoltarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 70));

        lblfundoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoCadastro.png"))); // NOI18N
        lblfundoCadastro.setPreferredSize(new java.awt.Dimension(1366, 750));
        pessoaJuridica.add(lblfundoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        cardPane.add(pessoaJuridica, "pessoaJuridica");

        endereco.setBackground(new java.awt.Color(255, 255, 255));
        endereco.setPreferredSize(new java.awt.Dimension(1366, 750));
        endereco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleLocalizacao.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitleLocalizacao.setText("LOCALIZAÇÃO");
        lblTitleLocalizacao.setToolTipText("");

        lblCep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCep.setText("CEP");
        lblCep.setToolTipText("");

        txtUf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBairro.setText("BAIRRO*");
        lblBairro.setToolTipText("");

        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblRua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRua.setText("RUA*");
        lblRua.setToolTipText("");

        lblUf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUf.setText("UF*");
        lblUf.setToolTipText("");

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCidade.setText("CIDADE*");
        lblCidade.setToolTipText("");

        txtRua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnProximoEndereco.setBackground(new java.awt.Color(255, 153, 0));
        btnProximoEndereco.setForeground(new java.awt.Color(255, 255, 255));
        btnProximoEndereco.setText("Próximo");
        btnProximoEndereco.setArc(20);
        btnProximoEndereco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProximoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoEnderecoActionPerformed(evt);
            }
        });

        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumero.setText("NÚMERO*");
        lblNumero.setToolTipText("");

        lblComplemento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblComplemento.setText("COMPLEMENTO");
        lblComplemento.setToolTipText("");

        txtComplemento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblErroCampoNuloEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblErroCampoNuloEndereco.setForeground(new java.awt.Color(255, 0, 51));
        lblErroCampoNuloEndereco.setText("Preencha todos os campos obrigatórios");

        javax.swing.GroupLayout encloseLocalizacaoLayout = new javax.swing.GroupLayout(encloseLocalizacao);
        encloseLocalizacao.setLayout(encloseLocalizacaoLayout);
        encloseLocalizacaoLayout.setHorizontalGroup(
            encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblCep)
                        .addGap(72, 72, 72)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblTitleLocalizacao)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUf)
                    .addComponent(lblCidade)
                    .addComponent(lblBairro)
                    .addComponent(lblRua)
                    .addComponent(lblNumero)
                    .addComponent(lblComplemento))
                .addGap(6, 6, 6)
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplemento))
                .addGap(36, 36, 36))
            .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnProximoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encloseLocalizacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErroCampoNuloEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        encloseLocalizacaoLayout.setVerticalGroup(
            encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitleLocalizacao)
                .addGap(79, 79, 79)
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCep, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblUf))
                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblCidade))
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblBairro))
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblRua))
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(encloseLocalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encloseLocalizacaoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblComplemento))
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblErroCampoNuloEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProximoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        endereco.add(encloseLocalizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 480, 660));

        btnVoltarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltarVerde.png"))); // NOI18N
        btnVoltarEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarEnderecoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarEnderecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarEnderecoMouseExited(evt);
            }
        });
        endereco.add(btnVoltarEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 70));

        lblFundoLocalizacao.setBackground(new java.awt.Color(255, 255, 255));
        lblFundoLocalizacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoLocalizacao.png"))); // NOI18N
        endereco.add(lblFundoLocalizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cardPane.add(endereco, "endereco");

        seuInteresse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltarInteresse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltarVerde.png"))); // NOI18N
        btnVoltarInteresse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarInteresseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarInteresseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarInteresseMouseExited(evt);
            }
        });
        seuInteresse.add(btnVoltarInteresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 70));

        btnAdquirir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AdquirirIcon.png"))); // NOI18N
        btnAdquirir.setToolTipText("Clique");
        btnAdquirir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdquirir.setPreferredSize(new java.awt.Dimension(50, 20));
        btnAdquirir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdquirirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdquirirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdquirirMouseExited(evt);
            }
        });
        seuInteresse.add(btnAdquirir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 310, 290));

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DescartarIcon.png"))); // NOI18N
        btnDescartar.setToolTipText("Clique");
        btnDescartar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDescartar.setPreferredSize(new java.awt.Dimension(50, 20));
        btnDescartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescartarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDescartarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDescartarMouseExited(evt);
            }
        });
        seuInteresse.add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 310, 290));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitle.setText("SEU INTERESSE É:");
        seuInteresse.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 540, 110));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seuInteresseFundo.png"))); // NOI18N
        lblFundo.setPreferredSize(new java.awt.Dimension(1366, 750));
        seuInteresse.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        cardPane.add(seuInteresse, "interesse");

        tipoResiduos.setBackground(new java.awt.Color(255, 255, 255));
        tipoResiduos.setPreferredSize(new java.awt.Dimension(1366, 750));
        tipoResiduos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleTiposResiduos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitleTiposResiduos.setText("QUE SUA EMPRESA TRABALHA:");
        tipoResiduos.add(lblTitleTiposResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 780, -1));

        lblTitleTiposResiduos1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitleTiposResiduos1.setText("INFORME OS TIPOS DE RESÍDUOS");
        tipoResiduos.add(lblTitleTiposResiduos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 810, -1));

        btnVoltarTipoResiduos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltarLaranja.png"))); // NOI18N
        btnVoltarTipoResiduos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarTipoResiduosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarTipoResiduosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarTipoResiduosMouseExited(evt);
            }
        });
        tipoResiduos.add(btnVoltarTipoResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 70));

        btnProximoResiduo.setBackground(new java.awt.Color(7, 99, 36));
        btnProximoResiduo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnProximoResiduo.setForeground(new java.awt.Color(255, 255, 255));
        btnProximoResiduo.setText("Próximo");
        btnProximoResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoResiduoActionPerformed(evt);
            }
        });
        tipoResiduos.add(btnProximoResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 290, 80));

        lblErroTipoResiduo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblErroTipoResiduo.setForeground(new java.awt.Color(255, 0, 51));
        lblErroTipoResiduo.setText("Preencha ao menos 1 tipo de resíduo");
        tipoResiduos.add(lblErroTipoResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 330, -1));

        lblFundoTipoResiduos.setBackground(new java.awt.Color(255, 255, 255));
        lblFundoTipoResiduos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoTiposResiduo.png"))); // NOI18N
        tipoResiduos.add(lblFundoTipoResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        lblCapacidadeMax1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCapacidadeMax1.setText("CAPACIDADE MÁXIMA:");
        lblCapacidadeMax1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tipoResiduos.add(lblCapacidadeMax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 260, -1));

        txtCapPapel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCapPapel.setEnabled(false);
        txtCapPapel.setName("PAPEL"); // NOI18N
        tipoResiduos.add(txtCapPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 160, -1));

        rbtnPlastico.setBackground(new java.awt.Color(255, 255, 255));
        rbtnPlastico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtnPlastico.setText("PLÁSTICO");
        rbtnPlastico.setName("PLASTICO"); // NOI18N
        rbtnPlastico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPlasticoActionPerformed(evt);
            }
        });
        tipoResiduos.add(rbtnPlastico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 130, 40));

        lblKgMetal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKgMetal.setText("kg");
        tipoResiduos.add(lblKgMetal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 40, -1));

        txtCapVidro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCapVidro.setEnabled(false);
        txtCapVidro.setName("VIDRO"); // NOI18N
        tipoResiduos.add(txtCapVidro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 160, -1));

        rbtnVidro.setBackground(new java.awt.Color(255, 255, 255));
        rbtnVidro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtnVidro.setText("VIDRO");
        rbtnVidro.setName("VIDRO"); // NOI18N
        rbtnVidro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVidroActionPerformed(evt);
            }
        });
        tipoResiduos.add(rbtnVidro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 130, 40));

        txtCapMetal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCapMetal.setToolTipText("");
        txtCapMetal.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCapMetal.setEnabled(false);
        txtCapMetal.setName("METAL"); // NOI18N
        tipoResiduos.add(txtCapMetal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 160, -1));
        txtCapMetal.getAccessibleContext().setAccessibleName("METAL");

        txtPrecoVidro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPrecoVidro.setEnabled(false);
        txtPrecoVidro.setName("VIDRO"); // NOI18N
        tipoResiduos.add(txtPrecoVidro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 140, -1));

        rbtnPapel.setBackground(new java.awt.Color(255, 255, 255));
        rbtnPapel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtnPapel.setText("PAPEL");
        rbtnPapel.setName("PAPEL"); // NOI18N
        rbtnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPapelActionPerformed(evt);
            }
        });
        tipoResiduos.add(rbtnPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 120, 40));

        rbtnMetal.setBackground(new java.awt.Color(255, 255, 255));
        rbtnMetal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtnMetal.setText("METAL");
        rbtnMetal.setName("METAL"); // NOI18N
        rbtnMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMetalActionPerformed(evt);
            }
        });
        tipoResiduos.add(rbtnMetal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 130, 40));

        lblKgPlastico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKgPlastico.setText("kg");
        tipoResiduos.add(lblKgPlastico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 30, -1));

        lblKgVidro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKgVidro.setText("kg");
        tipoResiduos.add(lblKgVidro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 30, -1));

        txtPrecoMetal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPrecoMetal.setToolTipText("");
        txtPrecoMetal.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtPrecoMetal.setEnabled(false);
        txtPrecoMetal.setName("METAL"); // NOI18N
        tipoResiduos.add(txtPrecoMetal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 140, -1));
        txtPrecoMetal.getAccessibleContext().setAccessibleName("METAL");

        txtCapPlastico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCapPlastico.setEnabled(false);
        txtCapPlastico.setName("PLASTICO"); // NOI18N
        tipoResiduos.add(txtCapPlastico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 160, -1));

        lblKgMetal1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKgMetal1.setText("R$");
        tipoResiduos.add(lblKgMetal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 30, -1));

        lblKgPapel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKgPapel1.setText("R$");
        tipoResiduos.add(lblKgPapel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 30, -1));

        lblTipos1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTipos1.setText("   TIPOS:");
        lblTipos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tipoResiduos.add(lblTipos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 120, -1));

        lblKgPapel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKgPapel.setText("kg");
        tipoResiduos.add(lblKgPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 40, -1));

        txtPrecoPlastico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPrecoPlastico.setEnabled(false);
        txtPrecoPlastico.setName("PLASTICO"); // NOI18N
        tipoResiduos.add(txtPrecoPlastico, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 140, -1));

        lblPreco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPreco.setText("PREÇO/KG:");
        lblPreco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tipoResiduos.add(lblPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 130, -1));

        txtPrecoPapel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPrecoPapel.setEnabled(false);
        txtPrecoPapel.setName("PAPEL"); // NOI18N
        tipoResiduos.add(txtPrecoPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 140, -1));

        lblKgVidro1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKgVidro1.setText("R$");
        tipoResiduos.add(lblKgVidro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 30, -1));

        lblKgPlastico1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKgPlastico1.setText("R$");
        tipoResiduos.add(lblKgPlastico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 30, -1));

        cardPane.add(tipoResiduos, "tipoResiduos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void adicionarAoBD() {
        daoEmp.addEmpresa(empresa);
        daoUser.addUsuario(usuario);
    }
    private void btnDescartarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescartarMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/DescartarIconSelected.png"));
        btnDescartar.setIcon(icone);
    }//GEN-LAST:event_btnDescartarMouseEntered

    private void btnDescartarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescartarMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/DescartarIcon.png"));
        btnDescartar.setIcon(icone);
    }//GEN-LAST:event_btnDescartarMouseExited

    private void btnAdquirirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdquirirMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/AdquirirIconSelected.png"));
        btnAdquirir.setIcon(icone);
    }//GEN-LAST:event_btnAdquirirMouseEntered

    private void btnAdquirirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdquirirMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/AdquirirIcon.png"));
        btnAdquirir.setIcon(icone);
    }//GEN-LAST:event_btnAdquirirMouseExited

    private void btnVoltarInteresseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarInteresseMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerdeSelected.png"));
        btnVoltarInteresse.setIcon(icone);
    }//GEN-LAST:event_btnVoltarInteresseMouseEntered

    private void btnVoltarInteresseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarInteresseMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerde.png"));
        btnVoltarInteresse.setIcon(icone);
    }//GEN-LAST:event_btnVoltarInteresseMouseExited

    private void btnVoltarCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadastroMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerdeSelected.png"));
        btnVoltarCadastro.setIcon(icone);
    }//GEN-LAST:event_btnVoltarCadastroMouseEntered

    private void btnVoltarCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadastroMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerde.png"));
        btnVoltarCadastro.setIcon(icone);
    }//GEN-LAST:event_btnVoltarCadastroMouseExited

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        //CardLayout cl = (CardLayout) cardPane.getLayout();
        //cl.show(cardPane, "endereco");
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnVoltarInteresseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarInteresseMouseClicked
        CardLayout cl = (CardLayout) cardPane.getLayout();
        cl.show(cardPane, "endereco");
    }//GEN-LAST:event_btnVoltarInteresseMouseClicked

    private void btnVoltarCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadastroMouseClicked
        Window.getOwnerlessWindows()[0].setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarCadastroMouseClicked

    private void btnVoltarEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarEnderecoMouseClicked
        CardLayout cl = (CardLayout) cardPane.getLayout();
        cl.show(cardPane, "pessoaJuridica");
    }//GEN-LAST:event_btnVoltarEnderecoMouseClicked

    private void btnVoltarEnderecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarEnderecoMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerdeSelected.png"));
        btnVoltarEndereco.setIcon(icone);
    }//GEN-LAST:event_btnVoltarEnderecoMouseEntered

    private void btnVoltarEnderecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarEnderecoMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerde.png"));
        btnVoltarEndereco.setIcon(icone);
    }//GEN-LAST:event_btnVoltarEnderecoMouseExited

    private void btnVoltarTipoResiduosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarTipoResiduosMouseClicked
        CardLayout cl = (CardLayout) cardPane.getLayout();
        cl.show(cardPane, "interesse");
    }//GEN-LAST:event_btnVoltarTipoResiduosMouseClicked

    private void btnVoltarTipoResiduosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarTipoResiduosMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarLaranjaSelected.png"));
        btnVoltarTipoResiduos.setIcon(icone);
    }//GEN-LAST:event_btnVoltarTipoResiduosMouseEntered

    private void btnVoltarTipoResiduosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarTipoResiduosMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarLaranja.png"));
        btnVoltarTipoResiduos.setIcon(icone);
    }//GEN-LAST:event_btnVoltarTipoResiduosMouseExited

    private void btnAdquirirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdquirirMouseClicked
        // Takeshi-Naoki Ação para aparecer a tela de seleção dos tipos de resíduos que a empresa recicla ao selecionar o botão 
        // de que quer adquirir resíduos. Card Layout muda a prioridade dos frames que aparecem na tela.
        CardLayout cl = (CardLayout) cardPane.getLayout();
        cl.show(cardPane, "tipoResiduos");
        empresa.interesse = empresa.COMPRA;
    }//GEN-LAST:event_btnAdquirirMouseClicked

    private void btnDescartarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescartarMouseClicked
        // Na tela seuInteresse se a pessoa clicar que é produtora de resíduos ela já conclui o cadastro e é levada direto ao menu principal. 
        empresa.interesse = empresa.VENDA;
        adicionarAoBD();
        this.dispose();
        FrmMenu menu = new FrmMenu(usuario);
        menu.setVisible(true);
        JOptionPane.showMessageDialog(this, "Conta criada com sucesso! Bem vindo(a)"+empresa.nomeFantasia+". Para negociar clique em 'Procurar Empresas'. ");
    }//GEN-LAST:event_btnDescartarMouseClicked

    private void rbtnMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMetalActionPerformed
         // TN com esse código eu quero permitir a edição da capacidade Máx e preço apenas se o botão estiver marcado.
         if (rbtnMetal.isSelected()) {
             txtCapMetal.setEnabled(true);
             txtPrecoMetal.setEnabled(true);
             txtPrecoMetal.setText("");
             
     
        }else{
             txtCapMetal.setEnabled(false);
             txtCapMetal.setText("");
         }

    }//GEN-LAST:event_rbtnMetalActionPerformed

    private void rbtnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPapelActionPerformed
        if (rbtnPapel.isSelected()) {
             txtCapPapel.setEnabled(true);
             txtPrecoPapel.setEnabled(true);
             txtPrecoPapel.setText("");
     
        }else{
             txtCapPapel.setEnabled(false);
             txtCapPapel.setText("");
         }
    }//GEN-LAST:event_rbtnPapelActionPerformed

    private void rbtnPlasticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPlasticoActionPerformed
         if (rbtnPlastico.isSelected()) {
             txtCapPlastico.setEnabled(true);
             txtPrecoPlastico.setEnabled(true);
             txtPrecoPlastico.setText("");
     
        }else{
             txtCapPlastico.setEnabled(false);
             txtCapPlastico.setText("");
         }
    }//GEN-LAST:event_rbtnPlasticoActionPerformed

    private void rbtnVidroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVidroActionPerformed
         if (rbtnVidro.isSelected()) {
             txtCapVidro.setEnabled(true);
             txtPrecoVidro.setEnabled(true);
             txtPrecoVidro.setText("");
     
        }else{
             txtCapVidro.setEnabled(false);
             txtCapVidro.setText("");
         }
    }//GEN-LAST:event_rbtnVidroActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // Validação da senha
        if (Arrays.equals(pwdConfirmarSenha.getPassword(), pwdSenha.getPassword())) {
            usuario.senha = String.valueOf(pwdSenha.getPassword());
        }else {
            JOptionPane.showMessageDialog(this, "O valor do campo SENHA e CONFIRMAR SENHA devem ser iguais", "Diveregência entre as senhas", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        // TN Validando campos nulos comparando se a string está vazia
        if (txtRazaoSocial.getText().isBlank() 
            || txtCnpj.getText().isBlank()
            || txtNomeFantasia.getText().isBlank()
            || txtEmail.getText().isBlank()
            || txtTelefone.getText().isBlank()
        ){
            lblErroCampoNulo.setVisible(true);
        }
        
        else{
            CardLayout cl = (CardLayout) cardPane.getLayout();
            cl.show(cardPane, "endereco");
            lblErroCampoNulo.setVisible(false);
        }
        // TN Preencher empresa
        empresa.razaoSocial = txtRazaoSocial.getText();
        empresa.nomeFantasia = txtNomeFantasia.getText();
        empresa.cnpj = txtCnpj.getText();
        empresa.site = txtSite.getText();
        empresa.email = txtEmail.getText();
        empresa.telefone = txtTelefone.getText();
        usuario.login = empresa.email;
        usuario.cnpjEmpresa = empresa.cnpj;
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void pwdConfirmarSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdConfirmarSenhaFocusLost
        if (Arrays.equals(pwdConfirmarSenha.getPassword(), pwdSenha.getPassword())) {
            pwdConfirmarSenha.setForeground(Color.black);
        } 
        else {
            pwdConfirmarSenha.setForeground(Color.red);
        }
    }//GEN-LAST:event_pwdConfirmarSenhaFocusLost

    private void pwdSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdSenhaFocusLost
        if (Arrays.equals(pwdConfirmarSenha.getPassword(), pwdSenha.getPassword())) {
            pwdConfirmarSenha.setForeground(Color.black);
        } 
        else {
            pwdConfirmarSenha.setForeground(Color.red);
        }
    }//GEN-LAST:event_pwdSenhaFocusLost
    
    // TN Preencher residuo apenas se o botao estiver marcado. Função usada no evento abaixo
    private void addResiduo(int tipo, JRadioButton rButton, JTextField txtCap, JTextField txtPreco) {
        if (rButton.isSelected()) {
            Residuo r = new Residuo();
            r.tipoResiduo = tipo;
            r.capacidade = Double.valueOf(txtCap.getText());
            r.preco = Double.valueOf(txtPreco.getText());
            r.cnpjEmpresa = empresa.cnpj;
            r.quantidadeAtual = 0.0;
            
            residuos.add(r);
        }
    }
    private void btnProximoResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoResiduoActionPerformed
        // TN Pra cada linha, se o botão estiver selecionado, checar os campos, se não, retorna true ignorando a validacao
        if (   rbtnMetal.isSelected() ? txtCapMetal.getText().isBlank() || txtPrecoMetal.getText().isBlank() : true
            && rbtnPapel.isSelected() ? txtCapPapel.getText().isBlank() || txtPrecoPapel.getText().isBlank() : true
            && rbtnPlastico.isSelected() ? txtCapPlastico.getText().isBlank() || txtPrecoPlastico.getText().isBlank() : true
            && rbtnVidro.isSelected() ? txtCapVidro.getText().isBlank() || txtPrecoVidro.getText().isBlank() : true
        ){
            lblErroTipoResiduo.setVisible(true);
            return;
        }
        lblErroTipoResiduo.setVisible(false);
        
        // TN preencher lista
        addResiduo(Residuo.METAL, rbtnMetal, txtCapMetal, txtPrecoMetal);
        addResiduo(Residuo.PAPEL, rbtnPapel, txtCapPapel, txtPrecoPapel);
        addResiduo(Residuo.PLASTICO, rbtnPlastico, txtCapPlastico, txtPrecoPlastico);
        addResiduo(Residuo.VIDRO, rbtnVidro, txtCapVidro, txtPrecoVidro);
        
        // TN Adicionar ao banco de dados
        adicionarAoBD();
        for (Residuo r: residuos) {
            daoRes.addResiduo(r);
        }
        
        JOptionPane.showMessageDialog(this, "Conta criada com sucesso! Bem vindo(a)"+empresa.nomeFantasia+". Para negociar clique em 'Procurar Empresas'. ");
        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProximoResiduoActionPerformed

    private void btnProximoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoEnderecoActionPerformed
        if (
            txtCep.getText().isBlank()
            || txtUf.getText().isBlank()
            || txtCidade.getText().isBlank()
            || txtBairro.getText().isBlank()
            || txtRua.getText().isBlank()
            || txtNumero.getText().isBlank()
        ){ 
            lblErroCampoNuloEndereco.setVisible(true);
        }
        else{
            CardLayout cl = (CardLayout) cardPane.getLayout();
            cl.show(cardPane, "interesse");
            lblErroCampoNuloEndereco.setVisible(false);
            
            empresa.cep = txtCep.getText();
            empresa.uf = txtUf.getText();
            empresa.cidade = txtCidade.getText();
            empresa.bairro = txtBairro.getText();
            empresa.rua = txtRua.getText();
            empresa.numero = txtNumero.getText();
            empresa.complemento = txtComplemento.getText();
        }
            
    }//GEN-LAST:event_btnProximoEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdquirir;
    private Swing.JButtonRound btnCadastrar;
    private javax.swing.JLabel btnDescartar;
    private Swing.JButtonRound btnProximoEndereco;
    private javax.swing.JButton btnProximoResiduo;
    private javax.swing.JLabel btnVoltarCadastro;
    private javax.swing.JLabel btnVoltarEndereco;
    private javax.swing.JLabel btnVoltarInteresse;
    private javax.swing.JLabel btnVoltarTipoResiduos;
    private javax.swing.JPanel cardPane;
    private javax.swing.JPanel encloseLocalizacao;
    private javax.swing.JPanel endereco;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCapacidadeMax1;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblErroCampoNulo;
    private javax.swing.JLabel lblErroCampoNuloEndereco;
    private javax.swing.JLabel lblErroTipoResiduo;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblFundoLocalizacao;
    private javax.swing.JLabel lblFundoTipoResiduos;
    private javax.swing.JLabel lblKgMetal;
    private javax.swing.JLabel lblKgMetal1;
    private javax.swing.JLabel lblKgPapel;
    private javax.swing.JLabel lblKgPapel1;
    private javax.swing.JLabel lblKgPlastico;
    private javax.swing.JLabel lblKgPlastico1;
    private javax.swing.JLabel lblKgVidro;
    private javax.swing.JLabel lblKgVidro1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTipos1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleLocalizacao;
    private javax.swing.JLabel lblTitleTiposResiduos;
    private javax.swing.JLabel lblTitleTiposResiduos1;
    private javax.swing.JLabel lblTituloPessoaJuridica;
    private javax.swing.JLabel lblUf;
    private javax.swing.JLabel lblfundoCadastro;
    private javax.swing.JPanel pessoaJuridica;
    private javax.swing.JPanel pessoaJuridicaPane;
    private javax.swing.JPasswordField pwdConfirmarSenha;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JRadioButton rbtnMetal;
    private javax.swing.JRadioButton rbtnPapel;
    private javax.swing.JRadioButton rbtnPlastico;
    private javax.swing.JRadioButton rbtnVidro;
    private javax.swing.JPanel seuInteresse;
    private javax.swing.JPanel tipoResiduos;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCapMetal;
    private javax.swing.JTextField txtCapPapel;
    private javax.swing.JTextField txtCapPlastico;
    private javax.swing.JTextField txtCapVidro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecoMetal;
    private javax.swing.JTextField txtPrecoPapel;
    private javax.swing.JTextField txtPrecoPlastico;
    private javax.swing.JTextField txtPrecoVidro;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUf;
    // End of variables declaration//GEN-END:variables
}
