/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author Takeshi
 */
public class FrmCadastroTela extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroTela
     */
    public FrmCadastroTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAdquirir = new javax.swing.JLabel();
        btnDescartar = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdquirir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AdquirirIcon.png"))); // NOI18N
        btnAdquirir.setToolTipText("Clique");
        btnAdquirir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdquirir.setPreferredSize(new java.awt.Dimension(50, 20));
        btnAdquirir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdquirirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdquirirMouseExited(evt);
            }
        });
        jPanel1.add(btnAdquirir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 310, 290));

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DescartarIcon.png"))); // NOI18N
        btnDescartar.setToolTipText("Clique");
        btnDescartar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDescartar.setPreferredSize(new java.awt.Dimension(50, 20));
        btnDescartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDescartarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDescartarMouseExited(evt);
            }
        });
        jPanel1.add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 310, 290));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitle.setText("SEU INTERESSE É:");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 540, 110));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seuInteresseFundo.png"))); // NOI18N
        jPanel1.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout cardPaneLayout = new javax.swing.GroupLayout(cardPane);
        cardPane.setLayout(cardPaneLayout);
        cardPaneLayout.setHorizontalGroup(
            cardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(cardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardPaneLayout.setVerticalGroup(
            cardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(cardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescartarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescartarMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/DescartarIconSelected.png"));
        btnDescartar.setIcon(icone);
    }//GEN-LAST:event_btnDescartarMouseEntered

    private void btnDescartarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescartarMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/DescartarIcon.png"));
        btnDescartar.setIcon(icone);
    }//GEN-LAST:event_btnDescartarMouseExited

    private void btnAdquirirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdquirirMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/AdquirirIconSelected.png"));
        btnAdquirir.setIcon(icone);
    }//GEN-LAST:event_btnAdquirirMouseEntered

    private void btnAdquirirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdquirirMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/AdquirirIcon.png"));
        btnAdquirir.setIcon(icone);
    }//GEN-LAST:event_btnAdquirirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdquirir;
    private javax.swing.JLabel btnDescartar;
    private javax.swing.JPanel cardPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
