/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Takeshi
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu1
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDesktopMain = new javax.swing.JDesktopPane();
        mainLayeredPane = new javax.swing.JLayeredPane();
        btn3Pontos = new javax.swing.JButton();
        UserIcon = new javax.swing.JLabel();
        nomeUsuario = new javax.swing.JLabel();
        jPanelBarraVerde = new javax.swing.JPanel();
        btnCadastroVerde = new javax.swing.JButton();
        btnSuporte = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        cardPane = new javax.swing.JPanel();
        homePane = new javax.swing.JLayeredPane();
        vamosTornar = new javax.swing.JLabel();
        mundoMelhor = new javax.swing.JLabel();
        logoSoma = new javax.swing.JLabel();
        btnSaibaMais = new javax.swing.JButton();
        cadastroPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        quemSomosPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOMA");

        mainLayeredPane.setBackground(new java.awt.Color(242, 242, 242));
        mainLayeredPane.setBorder(new javax.swing.border.MatteBorder(null));
        mainLayeredPane.setPreferredSize(new java.awt.Dimension(1366, 768));
        mainLayeredPane.setRequestFocusEnabled(false);
        mainLayeredPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3Pontos.setForeground(new java.awt.Color(255, 255, 255));
        btn3Pontos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menuIcon.png"))); // NOI18N
        btn3Pontos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn3Pontos.setContentAreaFilled(false);
        btn3Pontos.setDisabledIcon(null);
        btn3Pontos.setFocusCycleRoot(true);
        btn3Pontos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3PontosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3PontosMouseExited(evt);
            }
        });
        btn3Pontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3PontosActionPerformed(evt);
            }
        });
        mainLayeredPane.add(btn3Pontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 30, -1, 53));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile-user 64px.png"))); // NOI18N
        mainLayeredPane.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 47, -1, -1));

        nomeUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomeUsuario.setText("Olá, Nome do Usuário");
        mainLayeredPane.add(nomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1058, 44, 192, 67));

        jPanelBarraVerde.setBackground(new java.awt.Color(7, 99, 36));
        jPanelBarraVerde.setForeground(new java.awt.Color(7, 99, 36));

        btnCadastroVerde.setBackground(new java.awt.Color(0, 102, 0));
        btnCadastroVerde.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastroVerde.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastroVerde.setText("CADASTRO");
        btnCadastroVerde.setBorder(null);
        btnCadastroVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroVerdeActionPerformed(evt);
            }
        });

        btnSuporte.setBackground(new java.awt.Color(0, 102, 0));
        btnSuporte.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSuporte.setForeground(new java.awt.Color(255, 255, 255));
        btnSuporte.setText("SUPORTE");
        btnSuporte.setBorder(null);
        btnSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporteActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(0, 102, 0));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("INICIO");
        btnInicio.setBorder(null);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBarraVerdeLayout = new javax.swing.GroupLayout(jPanelBarraVerde);
        jPanelBarraVerde.setLayout(jPanelBarraVerdeLayout);
        jPanelBarraVerdeLayout.setHorizontalGroup(
            jPanelBarraVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarraVerdeLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCadastroVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSuporte, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBarraVerdeLayout.setVerticalGroup(
            jPanelBarraVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarraVerdeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelBarraVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuporte, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mainLayeredPane.add(jPanelBarraVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 142, 1364, -1));

        cardPane.setBackground(new java.awt.Color(255, 255, 255));
        cardPane.setBorder(new javax.swing.border.MatteBorder(null));
        cardPane.setLayout(new java.awt.CardLayout());

        homePane.setBackground(new java.awt.Color(255, 255, 255));
        homePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vamosTornar.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        vamosTornar.setForeground(new java.awt.Color(7, 99, 36));
        vamosTornar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vamosTornar.setText("VAMOS TORNAR O\n");
        vamosTornar.setToolTipText("");
        homePane.add(vamosTornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 112, -1, 65));

        mundoMelhor.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        mundoMelhor.setForeground(new java.awt.Color(7, 99, 36));
        mundoMelhor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mundoMelhor.setText("MUNDO MELHOR?");
        mundoMelhor.setToolTipText("");
        homePane.add(mundoMelhor, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 183, 392, -1));

        logoSoma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo verde.png"))); // NOI18N
        homePane.add(logoSoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 52, -1, 317));

        btnSaibaMais.setBackground(new java.awt.Color(7, 99, 36));
        btnSaibaMais.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnSaibaMais.setForeground(new java.awt.Color(255, 255, 255));
        btnSaibaMais.setText("SAIBA MAIS");
        homePane.add(btnSaibaMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 253, 237, 57));

        cardPane.add(homePane, "home");

        jLabel1.setText("tela de cadastro");

        javax.swing.GroupLayout cadastroPaneLayout = new javax.swing.GroupLayout(cadastroPane);
        cadastroPane.setLayout(cadastroPaneLayout);
        cadastroPaneLayout.setHorizontalGroup(
            cadastroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPaneLayout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(jLabel1)
                .addContainerGap(923, Short.MAX_VALUE))
        );
        cadastroPaneLayout.setVerticalGroup(
            cadastroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPaneLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        cardPane.add(cadastroPane, "card3");

        quemSomosPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("QUEM SOMOS?");
        quemSomosPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 55, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("na busca por empresas homologadas próximas.");
        quemSomosPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 950, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("A plataforma tem como objetivo conectar indivíduos e/ou indústrias que geram");
        quemSomosPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 971, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("resíduos inorgânicos com empresas interessadas em adquirir tais resíduos para");
        quemSomosPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 950, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("reciclagem. Tem como campo de atuação o descarte sustentável, incluindo toda");
        quemSomosPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 950, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("a cadeia  de fornecedores e  compradores, controle  de  produção e  rastreio  de ");
        quemSomosPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 950, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("transporte.  Essas características convergem para a missão de auxiliar na gestão");
        quemSomosPane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 950, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("de respiduos inorgânicos, otimizando processos internos e economizando tempo");
        quemSomosPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 950, 40));

        cardPane.add(quemSomosPane, "card4");

        mainLayeredPane.add(cardPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 216, -1, -1));

        painelDesktopMain.setLayer(mainLayeredPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDesktopMainLayout = new javax.swing.GroupLayout(painelDesktopMain);
        painelDesktopMain.setLayout(painelDesktopMainLayout);
        painelDesktopMainLayout.setHorizontalGroup(
            painelDesktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        painelDesktopMainLayout.setVerticalGroup(
            painelDesktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktopMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktopMain)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroVerdeActionPerformed
//        CardLayout cl = (CardLayout) cardPane.getLayout();
//        cl.show(cardPane, "cadastroPane");
        cadastroPane.setVisible(true);
        homePane.setVisible(false);
        quemSomosPane.setVisible(false);

    }//GEN-LAST:event_btnCadastroVerdeActionPerformed

    private void btnSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporteActionPerformed
        quemSomosPane.setVisible(true);
        homePane.setVisible(false);
        cadastroPane.setVisible(false);
    }//GEN-LAST:event_btnSuporteActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
//        CardLayout cl = (CardLayout) cardPane.getLayout();
//        cl.show(cardPane, "homePane");
        homePane.setVisible(true);
        cadastroPane.setVisible(false);
        quemSomosPane.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btn3PontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3PontosActionPerformed
        InFrmMais mais = new InFrmMais();
        painelDesktopMain.add(mais);
        mais.setVisible(true);
        try {
            mais.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn3PontosActionPerformed

    private void btn3PontosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3PontosMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/menuIconSelected.png"));
        btn3Pontos.setIcon(icone);
    }//GEN-LAST:event_btn3PontosMouseEntered

    private void btn3PontosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3PontosMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/menuIcon.png"));
        btn3Pontos.setIcon(icone);
    }//GEN-LAST:event_btn3PontosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserIcon;
    private javax.swing.JButton btn3Pontos;
    private javax.swing.JButton btnCadastroVerde;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSaibaMais;
    private javax.swing.JButton btnSuporte;
    private javax.swing.JPanel cadastroPane;
    private javax.swing.JPanel cardPane;
    private javax.swing.JLayeredPane homePane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBarraVerde;
    private javax.swing.JLabel logoSoma;
    private javax.swing.JLayeredPane mainLayeredPane;
    private javax.swing.JLabel mundoMelhor;
    private javax.swing.JLabel nomeUsuario;
    private javax.swing.JDesktopPane painelDesktopMain;
    private javax.swing.JPanel quemSomosPane;
    private javax.swing.JLabel vamosTornar;
    // End of variables declaration//GEN-END:variables
}
