/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.DaoUsuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.*;
import model.Usuario;


/**
 *
 * @author Takeshi
 */
public class FrmUsuariosCadastrados extends javax.swing.JFrame {
    
    DaoUsuario daoUsuario = new DaoUsuario();
    List<Usuario> lista = new ArrayList<>();


    public FrmUsuariosCadastrados() {
        initComponents();
        
        lista = daoUsuario.getAll();
        preencherTabela();
    }
   
    public void preencherTabela(){
    //TN Preenche a tabela de acordo com o banco de dados.    
        
    tblUsuarios.getColumnModel().getColumn(0).setWidth(2); //PreferredWidth é a largura medida em pixels
    tblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(2);
    tblUsuarios.getColumnModel().getColumn(2).setPreferredWidth(30);
    tblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(20);
    
    DefaultTableModel modelo = (DefaultTableModel)tblUsuarios.getModel();
    modelo.setNumRows(0); //Limpar a tabela
    
    for(int i=0;i<lista.size();i++){
        modelo.addRow(new Object[]{
            lista.get(i).idUsuario,
            lista.get(i).tipo,
            lista.get(i).login,
            lista.get(i).cnpjEmpresa,

          
        });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitleUsuarios = new javax.swing.JLabel();
        btnVoltarUsuarios = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lblFundoUsuarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitleUsuarios.setText("USUÁRIOS CADASTRADOS");
        jPanel1.add(lblTitleUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        btnVoltarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltarVerde.png"))); // NOI18N
        btnVoltarUsuarios.setToolTipText("voltar");
        btnVoltarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarUsuariosMouseExited(evt);
            }
        });
        jPanel1.add(btnVoltarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 70));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdUser", "Tipo", "Login", "cnpjEmpresa"
            }
        ));
        scrollPane.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(2);
        }

        jPanel1.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 1070, 300));

        lblFundoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoUsuarios.png"))); // NOI18N
        jPanel1.add(lblFundoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarUsuariosMouseClicked
        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
        menu.setExtendedState(this.getExtendedState());
        this.dispose();
    }//GEN-LAST:event_btnVoltarUsuariosMouseClicked

    private void btnVoltarUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarUsuariosMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerdeSelected.png"));
        btnVoltarUsuarios.setIcon(icone);
    }//GEN-LAST:event_btnVoltarUsuariosMouseEntered

    private void btnVoltarUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarUsuariosMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerde.png"));
        btnVoltarUsuarios.setIcon(icone);
    }//GEN-LAST:event_btnVoltarUsuariosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuariosCadastrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnVoltarUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFundoUsuarios;
    private javax.swing.JLabel lblTitleUsuarios;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
