/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Usuario;
import static view.FrmMenu.empresa;

/**
 *
 * @author Admin
 */
public class InFrmMais extends javax.swing.JInternalFrame {
    Usuario usuario;
    /**
     * Creates new form InFrmMais
     */
    public InFrmMais(Usuario user) {
        initComponents();
        usuario = user;
        if (usuario.tipo==Usuario.EMPRESA) {
            btnUsuariosCadastrados.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnTransacoes = new javax.swing.JButton();
        btnProcurarEmpresas = new javax.swing.JButton();
        btnUsuariosCadastrados = new javax.swing.JButton();
        btnMapa = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(7, 99, 36));
        setBorder(null);
        setForeground(java.awt.Color.lightGray);
        setFrameIcon(null);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(7, 99, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setBackground(new java.awt.Color(59, 56, 58));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconExit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 120, 60));

        btnTransacoes.setBackground(new java.awt.Color(118, 118, 118));
        btnTransacoes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTransacoes.setForeground(new java.awt.Color(255, 255, 255));
        btnTransacoes.setText("HISTÓRICO DE TRANSAÇÕES");
        btnTransacoes.setBorder(null);
        btnTransacoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 370, 50));

        btnProcurarEmpresas.setBackground(new java.awt.Color(118, 118, 118));
        btnProcurarEmpresas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProcurarEmpresas.setForeground(new java.awt.Color(255, 255, 255));
        btnProcurarEmpresas.setText("PROCURAR EMPRESAS");
        btnProcurarEmpresas.setBorder(null);
        btnProcurarEmpresas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProcurarEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarEmpresasActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcurarEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 50));

        btnUsuariosCadastrados.setBackground(new java.awt.Color(118, 118, 118));
        btnUsuariosCadastrados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUsuariosCadastrados.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuariosCadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile-user.png"))); // NOI18N
        btnUsuariosCadastrados.setText("USUÁRIOS CADASTRADOS");
        btnUsuariosCadastrados.setBorder(null);
        btnUsuariosCadastrados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuariosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosCadastradosActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuariosCadastrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 230, 50));

        btnMapa.setBackground(new java.awt.Color(118, 118, 118));
        btnMapa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMapa.setForeground(new java.awt.Color(255, 255, 255));
        btnMapa.setText("MAPA PONTOS DE COLETA");
        btnMapa.setBorder(null);
        btnMapa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 330, 50));

        btnPerfil.setBackground(new java.awt.Color(118, 118, 118));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("MEU PERFIL");
        btnPerfil.setBorder(null);
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 50));

        lblFundo.setBackground(new java.awt.Color(0, 102, 51));
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/internalFrameMenuFundo.png"))); // NOI18N
        lblFundo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        FrmMenu.visible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if (this.getMousePosition(true)==null) {
            this.dispose();
        }
    }//GEN-LAST:event_formMouseExited

    private void btnTransacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransacoesActionPerformed
        FrmHistoricoTransacoes historico = new FrmHistoricoTransacoes();
        historico.setVisible(true);
        FrmMenu.visible(false);
    }//GEN-LAST:event_btnTransacoesActionPerformed

    private void btnProcurarEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarEmpresasActionPerformed
        FrmProcurarEmpresas transacao = new FrmProcurarEmpresas();
        transacao.setVisible(true);
        FrmMenu.visible(false);
    }//GEN-LAST:event_btnProcurarEmpresasActionPerformed

    private void btnUsuariosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosCadastradosActionPerformed
        FrmUsuariosCadastrados usuarios = new FrmUsuariosCadastrados();
        usuarios.setVisible(true);
        FrmMenu.visible(false);
    }//GEN-LAST:event_btnUsuariosCadastradosActionPerformed

    private void btnMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapaActionPerformed
        FrmMapa mapa = new FrmMapa();
        mapa.setVisible(true);
        FrmMenu.visible(false);
    }//GEN-LAST:event_btnMapaActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        if (FrmMenu.getEmpresa()==null) {
            JOptionPane.showMessageDialog(this, "Você está logado como administrador. Esse tipo de usuário não tem empresas cadastradas");
            return;
        }
        new FrmPerfil().setVisible(true);
        FrmMenu.visible(false);
    }//GEN-LAST:event_btnPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMapa;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnProcurarEmpresas;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTransacoes;
    private javax.swing.JButton btnUsuariosCadastrados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables
}
