/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class InFrmMais extends javax.swing.JInternalFrame {

    /**
     * Creates new form InFrmMais
     */
    public InFrmMais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnTransacoes = new javax.swing.JButton();
        btnProcurarEmpresas = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(7, 99, 36));
        setBorder(null);
        setForeground(java.awt.Color.lightGray);
        setFrameIcon(null);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(7, 99, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(59, 56, 58));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconExit.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 120, 60));

        btnTransacoes.setBackground(new java.awt.Color(118, 118, 118));
        btnTransacoes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTransacoes.setForeground(new java.awt.Color(255, 255, 255));
        btnTransacoes.setText("HISTÓRICO DE TRANSAÇÕES");
        btnTransacoes.setBorder(null);
        btnTransacoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 350, 50));

        btnProcurarEmpresas.setBackground(new java.awt.Color(118, 118, 118));
        btnProcurarEmpresas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProcurarEmpresas.setForeground(new java.awt.Color(255, 255, 255));
        btnProcurarEmpresas.setText("PROCURAR EMPRESAS");
        btnProcurarEmpresas.setBorder(null);
        btnProcurarEmpresas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProcurarEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarEmpresasActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcurarEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 50));

        btnPerfil.setBackground(new java.awt.Color(118, 118, 118));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("MEU PERFIL");
        btnPerfil.setBorder(null);
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 50));

        lblFundo.setBackground(new java.awt.Color(0, 102, 51));
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/internalFrameMenuFundo.png"))); // NOI18N
        lblFundo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if (this.getMousePosition(true)==null) {
            this.dispose();
        }
    }//GEN-LAST:event_formMouseExited

    private void btnTransacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransacoesActionPerformed
        FrmHistoricoTransacoes historico = new FrmHistoricoTransacoes();
        historico.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnTransacoesActionPerformed

    private void btnProcurarEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarEmpresasActionPerformed
        FrmTransacao transacao = new FrmTransacao();
        transacao.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnProcurarEmpresasActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        FrmPerfil perfil  = new FrmPerfil();
        perfil.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnProcurarEmpresas;
    private javax.swing.JButton btnTransacoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables
}
