/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author Takeshi
 */
public class pessoaJuridica extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroTela
     */
    public pessoaJuridica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPane = new javax.swing.JPanel();
        pessoaJuridica = new javax.swing.JPanel();
        pessoaJuridicaPane = new javax.swing.JPanel();
        lblTituloPessoaJuridica = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtConfirmarSenha = new javax.swing.JTextField();
        jButtonRound2 = new Swing.JButtonRound();
        btnVoltarCad = new javax.swing.JLabel();
        lblfundoCadastro = new javax.swing.JLabel();
        seuInteresse = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JLabel();
        btnAdquirir = new javax.swing.JLabel();
        btnDescartar = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        endereco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 750));

        cardPane.setPreferredSize(new java.awt.Dimension(1366, 750));
        cardPane.setLayout(new java.awt.CardLayout());

        pessoaJuridica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pessoaJuridicaPane.setBackground(new java.awt.Color(255, 255, 255));
        pessoaJuridicaPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));

        lblTituloPessoaJuridica.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloPessoaJuridica.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTituloPessoaJuridica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPessoaJuridica.setText("PESSOA JURÍDICA");

        txtNomeEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "NOME DA EMPRESA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "SITE (opicional)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "EMAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtTelefone.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "TELEFONE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "SENHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtConfirmarSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "CONFIRMAR SENHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jButtonRound2.setBackground(new java.awt.Color(255, 153, 0));
        jButtonRound2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRound2.setText("CADASTRAR");
        jButtonRound2.setArc(20);
        jButtonRound2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRound2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pessoaJuridicaPaneLayout = new javax.swing.GroupLayout(pessoaJuridicaPane);
        pessoaJuridicaPane.setLayout(pessoaJuridicaPaneLayout);
        pessoaJuridicaPaneLayout.setHorizontalGroup(
            pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pessoaJuridicaPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(454, 454, 454))
            .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addComponent(lblTituloPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                                    .addComponent(txtEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pessoaJuridicaPaneLayout.setVerticalGroup(
            pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoaJuridicaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pessoaJuridicaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pessoaJuridica.add(pessoaJuridicaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 1110, 460));

        btnVoltarCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltarVerde.png"))); // NOI18N
        btnVoltarCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarCadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarCadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarCadMouseExited(evt);
            }
        });
        pessoaJuridica.add(btnVoltarCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 70));

        lblfundoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoCadastro.png"))); // NOI18N
        lblfundoCadastro.setPreferredSize(new java.awt.Dimension(1366, 750));
        pessoaJuridica.add(lblfundoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        cardPane.add(pessoaJuridica, "pessoaJuridica");

        seuInteresse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltarVerde.png"))); // NOI18N
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });
        seuInteresse.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 70));

        btnAdquirir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AdquirirIcon.png"))); // NOI18N
        btnAdquirir.setToolTipText("Clique");
        btnAdquirir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdquirir.setPreferredSize(new java.awt.Dimension(50, 20));
        btnAdquirir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdquirirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdquirirMouseExited(evt);
            }
        });
        seuInteresse.add(btnAdquirir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 310, 290));

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DescartarIcon.png"))); // NOI18N
        btnDescartar.setToolTipText("Clique");
        btnDescartar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDescartar.setPreferredSize(new java.awt.Dimension(50, 20));
        btnDescartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDescartarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDescartarMouseExited(evt);
            }
        });
        seuInteresse.add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 310, 290));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitle.setText("SEU INTERESSE É:");
        seuInteresse.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 540, 110));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seuInteresseFundo.png"))); // NOI18N
        lblFundo.setPreferredSize(new java.awt.Dimension(1366, 750));
        seuInteresse.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        cardPane.add(seuInteresse, "interesse");

        endereco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        endereco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cardPane.add(endereco, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescartarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescartarMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/DescartarIconSelected.png"));
        btnDescartar.setIcon(icone);
    }//GEN-LAST:event_btnDescartarMouseEntered

    private void btnDescartarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescartarMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/DescartarIcon.png"));
        btnDescartar.setIcon(icone);
    }//GEN-LAST:event_btnDescartarMouseExited

    private void btnAdquirirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdquirirMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/AdquirirIconSelected.png"));
        btnAdquirir.setIcon(icone);
    }//GEN-LAST:event_btnAdquirirMouseEntered

    private void btnAdquirirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdquirirMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/AdquirirIcon.png"));
        btnAdquirir.setIcon(icone);
    }//GEN-LAST:event_btnAdquirirMouseExited

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerdeSelected.png"));
        btnVoltar.setIcon(icone);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerde.png"));
        btnVoltar.setIcon(icone);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnVoltarCadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadMouseEntered
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerdeSelected.png"));
        btnVoltarCad.setIcon(icone);
    }//GEN-LAST:event_btnVoltarCadMouseEntered

    private void btnVoltarCadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadMouseExited
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/voltarVerde.png"));
        btnVoltarCad.setIcon(icone);
    }//GEN-LAST:event_btnVoltarCadMouseExited

    private void jButtonRound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRound2MouseClicked
        CardLayout cl = (CardLayout) cardPane.getLayout();;
        cl.show(cardPane, "interesse");
    }//GEN-LAST:event_jButtonRound2MouseClicked

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        CardLayout cl = (CardLayout) cardPane.getLayout();;
        cl.show(cardPane, "pessoaJuridica");
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnVoltarCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadMouseClicked
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarCadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pessoaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pessoaJuridica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdquirir;
    private javax.swing.JLabel btnDescartar;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JLabel btnVoltarCad;
    private javax.swing.JPanel cardPane;
    private javax.swing.JPanel endereco;
    private Swing.JButtonRound jButtonRound2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTituloPessoaJuridica;
    private javax.swing.JLabel lblfundoCadastro;
    private javax.swing.JPanel pessoaJuridica;
    private javax.swing.JPanel pessoaJuridicaPane;
    private javax.swing.JPanel seuInteresse;
    private javax.swing.JTextField txtConfirmarSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
