/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teste;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Takeshi
 */
public class FrmTeste extends javax.swing.JFrame {

    /**
     * Creates new form FrmTeste
     */
    public FrmTeste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelJogador = new javax.swing.JPanel();
        spinnerScore = new javax.swing.JSpinner();
        btnResetar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        painelConf = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblJogadoresNum = new javax.swing.JLabel();
        spinnerJogadoresNum = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuResetar = new javax.swing.JMenu();
        menuComecar = new javax.swing.JMenu();

        painelJogador.setBackground(new java.awt.Color(204, 255, 255));

        spinnerScore.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        spinnerScore.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinnerScore.setName(""); // NOI18N

        btnResetar.setText("Resetar");
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNome.setText("Jogador");
        txtNome.setBorder(null);

        javax.swing.GroupLayout painelJogadorLayout = new javax.swing.GroupLayout(painelJogador);
        painelJogador.setLayout(painelJogadorLayout);
        painelJogadorLayout.setHorizontalGroup(
            painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelJogadorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNome)
                .addContainerGap())
        );
        painelJogadorLayout.setVerticalGroup(
            painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelJogadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetar)
                .addGap(27, 27, 27))
        );

        painelConf.setBackground(new java.awt.Color(204, 255, 255));
        painelConf.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Começar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblJogadoresNum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblJogadoresNum.setText("Numero de jogadores");

        spinnerJogadoresNum.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        spinnerJogadoresNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout painelConfLayout = new javax.swing.GroupLayout(painelConf);
        painelConf.setLayout(painelConfLayout);
        painelConfLayout.setHorizontalGroup(
            painelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConfLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(painelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJogadoresNum)
                    .addGroup(painelConfLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(spinnerJogadoresNum, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelConfLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        painelConfLayout.setVerticalGroup(
            painelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConfLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lblJogadoresNum)
                .addGap(18, 18, 18)
                .addComponent(spinnerJogadoresNum, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contador de Pontos");

        menuResetar.setText("Resetar");
        menuResetar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuResetarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuResetar);

        menuComecar.setText("Começar");
        menuComecar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuComecarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuComecar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        painelConf.setLocation(painelConf.getX()+5, painelConf.getY());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuResetarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuResetarMouseClicked
        dispose();
        new FrmTeste().setVisible(true);
    }//GEN-LAST:event_menuResetarMouseClicked

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        spinnerScore.setValue(0);
    }//GEN-LAST:event_btnResetarActionPerformed

    private void menuComecarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuComecarMouseClicked
        JPanel jogador = painelJogador;
        getContentPane().removeAll();
        getContentPane().add(jogador);
        jogador.setLocation(200, 200);
        jogador.setVisible(true);
        
        revalidate();
        repaint();
    }//GEN-LAST:event_menuComecarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetar;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblJogadoresNum;
    private javax.swing.JMenu menuComecar;
    private javax.swing.JMenu menuResetar;
    private javax.swing.JPanel painelConf;
    private javax.swing.JPanel painelJogador;
    private javax.swing.JSpinner spinnerJogadoresNum;
    private javax.swing.JSpinner spinnerScore;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
